#include<stdio.h>
int mx1,my1,mx2,my2,sta,end,sum,x1[200001],y1[200001],x2[200001],y2[200001];
double ans;
bool hash[200001];
inline int abs(int a)
{
       if(a>0)return a;
       return -a;
}
inline int dist(int x1,int y1,int x2,int y2)
{
       if(x1==x2)return abs(y1-y2);
       return abs(x1-x2);
}
int main()
{
    freopen("metamorphosis.in","r",stdin);
    freopen("metamorphosis.out","w",stdout);
    int i,j,len,xx1,yy1,xx2,yy2;
    scanf("%d%d%d%d",&mx1,&my1,&mx2,&my2);
    sta=1;
    end=1;
    sum=1;
    x1[1]=0;y1[1]=0;x2[1]=0;y2[1]=81;
    len=81;
    hash[1]=1;
    for(i=1;i<=4;i++)
    {
      len/=3;
      for(j=sta;j<=end;j++)
      {
        xx1=x1[j];
        yy1=y1[j];
        xx2=x2[j];
        yy2=y2[j];
        if(xx1==xx2)
        {
          if(yy1>yy2)
          {
            x1[++sum]=xx1;
            y1[sum]=yy2+len;
            x2[sum]=xx2;
            y2[sum]=yy2;
            x1[++sum]=xx1;
            y1[sum]=yy2+len;
            x2[sum]=xx2-len;
            y2[sum]=yy2+len;
            hash[sum]=1;
            x1[++sum]=xx1;
            y1[sum]=yy2+len;
            x2[sum]=xx2+len;
            y2[sum]=yy2+len;
            hash[sum]=1;
          }
          else
          {
            x1[++sum]=xx1;
            y1[sum]=yy2-len;
            x2[sum]=xx2;
            y2[sum]=yy2;
            x1[++sum]=xx1;
            y1[sum]=yy2-len;
            x2[sum]=xx2-len;
            y2[sum]=yy2-len;
            hash[sum]=1;
            x1[++sum]=xx1;
            y1[sum]=yy2-len;
            x2[sum]=xx2+len;
            y2[sum]=yy2-len;
            hash[sum]=1;
          }
        }
        else
        {
          if(xx1>xx2)
          {
            x1[++sum]=xx2+len;
            y1[sum]=yy1;
            x2[sum]=xx2;
            y2[sum]=yy2;
            x1[++sum]=xx2+len;
            y1[sum]=yy1;
            x2[sum]=xx2+len;
            y2[sum]=yy2-len;
            hash[sum]=1;
            x1[++sum]=xx2+len;
            y1[sum]=yy1;
            x2[sum]=xx2+len;
            y2[sum]=yy2+len;
            hash[sum]=1;
          }
          else
          {
            x1[++sum]=xx2-len;
            y1[sum]=yy1;
            x2[sum]=xx2;
            y2[sum]=yy2;
            x1[++sum]=xx2-len;
            y1[sum]=yy1;
            x2[sum]=xx2-len;
            y2[sum]=yy2-len;
            hash[sum]=1;
            x1[++sum]=xx2-len;
            y1[sum]=yy1;
            x2[sum]=xx2-len;
            y2[sum]=yy2+len;
            hash[sum]=1;
          }
        }
        if(hash[j]==0)continue;
        if(xx1==xx2)
        {
          if(xx1>mx2||xx1<mx1)continue;
          if(yy1>my2)yy1=my2;
          if(yy1<my1)yy1=my1;
          if(yy2>my2)yy2=my2;
          if(yy2<my1)yy2=my1;
        }
        else
        {
          if(yy2>my2||yy2<my1)continue;
          if(xx1>mx2)xx1=mx2;
          if(xx1<mx1)xx1=mx1;
          if(xx2>mx2)xx2=mx2;
          if(xx2<mx1)xx2=mx1;
        }
        ans+=dist(xx1,yy1,xx2,yy2);
      }
      sta=end+1;
      end=sum;
    }
    for(i=sta;i<=end;i++)
    {
      xx1=x1[i];
      yy1=y1[i];
      xx2=x2[i];
      yy2=y2[i];
      if(xx1==xx2)
      {
        if(xx1>mx2||xx1<mx1)continue;
        if(xx1==mx1||xx1==mx2)
        {
          if(yy1<=my1&&yy2<=my1||yy1>=my2&&yy2>=my2)continue;
          ans+=495.0*(2.0/3.0)/2;
          if(hash[i])ans+=1;
        }
        else
        {
          if(yy1<=my1&&yy2<=my1||yy1>=my2&&yy2>=my2)continue;
          ans+=495.0*(2.0/3.0);
          if(hash[i])ans+=1;
        }
      }
      else
      {
        if(yy1>my2||yy1<my1)continue;
        if(yy1==my1||yy1==my2)
        {
          if(xx1<=mx1&&xx2<=mx1||xx1>=mx2&&xx2>=mx2)continue;
          ans+=495.0*(2.0/3.0)/2;
          if(hash[i])ans+=1;
        }
        else
        {
          if(xx1<=mx1&&xx2<=mx1||xx1>=mx2&&xx2>=mx2)continue;
          ans+=495.0*(2.0/3.0);
          if(hash[i])ans+=1;
        }
      }
    }
    printf("%.1lf\n",ans);
    return 0;
}
